=== luowei/firefly-demo/doc/schema/beans.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:bean="http://code.google.com/p/firefly/beans"
        targetNamespace="http://code.google.com/p/firefly/beans"
        elementFormDefault="qualified">

    <element name="mvc">
        <complexType>
            <attribute name="view-path" />
            <attribute name="view-encoding" />
            <!-- <attribute name="view-type" />  -->
        </complexType>
    </element>
    <element name="import">
        <complexType>
            <attribute name="resource" />
        </complexType>
    </element>
    <element name="component-scan">
        <complexType>
            <attribute name="base-package" />
        </complexType>
    </element>
    <element name="value">
        <complexType mixed="true">
            <attribute name="type" />
        </complexType>
    </element>
    <element name="ref">
        <complexType>
            <attribute name="bean" />
        </complexType>
    </element>
    <element name="list">
        <complexType>
            <group ref="bean:collectionElements"></group>
            <attribute name="type" />
        </complexType>
    </element>
    <element name="array">
        <complexType>
            <group ref="bean:collectionElements"></group>
        </complexType>
    </element>
    <element name="map">
        <complexType>
            <sequence>
                <element name="entry" minOccurs="0" maxOccurs="unbounded">
                    <complexType>
                        <sequence>
                            <element name="key" minOccurs="0" maxOccurs="1">
                                <complexType mixed="true">
                                    <group ref="bean:mapElements"></group>
                                </complexType>
                            </element>
                            <element name="value" minOccurs="0" maxOccurs="1">
                                <complexType mixed="true">
                                    <group ref="bean:mapElements"></group>
                                </complexType>
                            </element>
                        </sequence>
                        <attribute name="key" />
                        <attribute name="value" />
                    </complexType>
                </element>
            </sequence>
            <attribute name="type" />
        </complexType>
    </element>
    <element name="bean">
        <complexType>
            <sequence>
                <element name="property" minOccurs="0" maxOccurs="unbounded">
                    <complexType>
                        <group ref="bean:propertyElements"></group>
                        <attribute name="name" use="required" />
                        <attribute name="value" />
                        <attribute name="ref" />
                    </complexType>
                </element>
            </sequence>
            <attribute name="id" />
            <attribute name="class" />
        </complexType>
    </element>

    <!-- 顶层元素 -->
    <element name="beans">
        <complexType>
            <sequence>
                <element ref="bean:import" minOccurs="0" maxOccurs="unbounded"></element>
                <element ref="bean:component-scan" minOccurs="0" maxOccurs="unbounded"></element>
                <element ref="bean:mvc" minOccurs="0" maxOccurs="1"></element>
                <element ref="bean:bean" minOccurs="0" maxOccurs="unbounded"></element>
            </sequence>
        </complexType>
        <unique name="idUnique">
            <selector xpath="bean:bean"></selector>
            <field xpath="@id"></field>
        </unique>
        <!-- <key name="beanKey">
            <selector xpath=".//bean:bean"></selector>
            <field xpath="@id"></field>
        </key>
        <keyref name="refKey" refer="bean:beanKey">
            <selector xpath=".//bean:ref"></selector>
            <field xpath="@bean"></field>
        </keyref>
        <keyref name="beanRefKey" refer="bean:beanKey">
            <selector xpath=".//bean:property"></selector>
            <field xpath="@ref"></field>
        </keyref> -->
    </element>

    <group name="collectionElements">
        <sequence>
            <choice minOccurs="0" maxOccurs="unbounded">
                <element ref="bean:value"></element>
                <element ref="bean:ref"></element>
                <element ref="bean:list"></element>
                <element ref="bean:array"></element>
                <element ref="bean:map"></element>
                <!-- <element ref="bean:bean"></element> -->
            </choice>
        </sequence>
    </group>
    <group name="propertyElements">
        <sequence>
            <choice minOccurs="0" maxOccurs="1">
                <element ref="bean:value"></element>
                <element ref="bean:ref"></element>
                <element ref="bean:list"></element>
                <element ref="bean:array"></element>
                <element ref="bean:map"></element>
                <!-- <element ref="bean:bean"></element> -->
            </choice>
        </sequence>
    </group>
    <group name="mapElements">
        <sequence>
            <choice minOccurs="0" maxOccurs="1">
                <element ref="bean:ref"></element>
                <element ref="bean:list"></element>
                <element ref="bean:array"></element>
                <element ref="bean:map"></element>
                <!-- <element ref="bean:bean"></element> -->
            </choice>
        </sequence>
    </group>
</schema>

=== luowei/firefly-demo/src/firefly.xml
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://code.google.com/p/firefly/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://code.google.com/p/firefly/beans http://firefly.googlecode.com/files/beans.xsd">

    <component-scan base-package="com.firefly"/>
    <mvc view-path="/template" view-encoding="UTF-8"/>

    <import resource="custom-beans.xml"/>

    <!--通过添加com.firefly.server.http.Config的bean来配置HTTP Server-->
    <bean class="com.firefly.server.http.Config">
        <property name="serverHome" value="D:/java_prj/my_project/firefly-demo/web"></property>
        <property name="host" value="localhost"></property>
        <property name="port" value="7676"></property>
        <property name="keepAlive" value="false"></property>
    </bean>




</beans>

=== luowei/firefly-demo/src/custom-beans.xml
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://code.google.com/p/firefly/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://code.google.com/p/firefly/beans http://firefly.googlecode.com/files/beans.xsd">


    <bean id="apple" class="com.firefly.demo.domain.Food">
        <property name="name" value="apple"/>
        <property name="price" value="5.3f"/>
    </bean>
    <bean id="orange" class="com.firefly.demo.domain.Food">
        <property name="name" value="orange"/>
        <property name="price" value="6.0f"/>
    </bean>
    <bean id="strawberry" class="com.firefly.demo.domain.Food">
        <property name="name" value="strawberry"/>
        <property name="price" value="10.00f"/>
    </bean>

    <bean id="foodRepository" class="com.firefly.demo.repository.FoodRepository">
        <property name="food">
            <list>
                <ref bean="apple"/>
                <ref bean="orange"/>
                <ref bean="strawberry"/>
            </list>
        </property>
    </bean>

</beans>
